# Generated by Django 5.1.1 on 2024-10-11 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_platform_track_platforms_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('track_name', models.CharField(max_length=100)),
                ('key', models.CharField(blank=True, max_length=2, null=True)),
                ('mode', models.CharField(blank=True, max_length=5, null=True)),
                ('bpm', models.FloatField(blank=True, null=True)),
                ('genres', models.TextField(blank=True)),
                ('related_artists', models.TextField(blank=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spotify_info', to='tracks.track')),
            ],
        ),
    ]
